### ISSUE TITLE
HTTP error when NASA posts a daily video instead of an image

### ISSUE THREAD

**Issue by brettvanderwerff** [ayan-b/Desktop-Wallpaper-Changer#12]
Today I get:
urllib.error.HTTPError: HTTP Error 404: Not Found

Its because NASA has a video today instead of a picture. You may want to revert to the last available picture 
when this error pops up.

**Comment by ayan-b** [comment]
Thanks for letting me know. I will do that. But it may happen that the user hadn't downloaded the last day's picture. In that case we have to fetch it from APoD archive. I will this particular functionally later. Currently it will just throw a "Not found" error.

**Comment by ayan-b** [comment]
@brettvanderwerff Solved this issue! In case a video is posted, it will scrap the website from the previous days until an image is found.
