### ISSUE TITLE
ModuleNotFoundError: No module named 'win32gui'

### ISSUE THREAD

**Issue by brettvanderwerff** [ayan-b/Desktop-Wallpaper-Changer#8]
Running on windows 64 bit got:

ModuleNotFoundError: No module named 'win32gui'

Fixed error by pip installing pywin32, maybe you need to add that to the requirements file.

**Comment by ayan-b** [comment]
Done!

**Comment by brettvanderwerff** [comment]
I did a pull request, that adresses this and another bug.
